name: qt macOS arm64 cd

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  macosbuild:
    strategy:
      matrix:
        os: [macos-13]
        arch: [arm64]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.8.3
          target: 'desktop'
          cache: 'true'
      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
          actions-cache-folder: '.xmake-cache'
      - name: xmake repo --update
        run: xmake repo --update
      - name: config
        run: xmake config -m release -a ${{ matrix.arch }} -vD --yes
      - name: build
        run: xmake build -vD --diagnosis stem
      - name: Generate DMG
        run: |
          # 设置环境变量以跳过代码签名（GitHub Actions 环境中通常没有开发者证书）
          export CODESIGN_IDENTITY="-"
          # 执行打包
          xmake install -vD stem_packager
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        with:
          name: stem-macos-arm64
          path: build/*.dmg
          retention-days: 30
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: build/*.dmg
